CUSTOM_LIBRETRO_CORES="\
                  2048 \
                  81 \
                  a5200 \
                  atari800 \
                  beetle_lynx \
                  beetle_ngp \
                  beetle_pce \
                  beetle_pce_fast \
                  beetle_pcfx \
                  beetle_psx \
                  beetle_saturn \
                  beetle_supafaust \
                  beetle_supergrafx \
                  beetle_vb \
                  beetle_wswan \
                  blastem \
                  bluemsx \
                  cannonball \
                  cap32 \
                  chailove \
                  citra \
                  craft \
                  crocods \
                  daphne \
                  desmume \
                  desmume_2015 \
                  dinothawr \
                  dolphin \
                  dosbox \
                  dosbox_pure \
                  dosbox_svn \
                  easyrpg \
                  emux_sms\
                  ecwolf \
                  fbneo \
                  fceumm \
                  flycast \
                  fmsx \
                  freechaf \
                  freeintv \
                  fuse_libretro \
                  gambatte \
                  gearboy \
                  gearsystem \
                  genesis_plus_gx \
                  genesis_plus_gx_wide \
                  gme \
                  gpsp \
                  gw_libretro \
                  handy \
                  hatari \
                  jumpnbump \
                  kronos \
                  lowres_nx \
                  lutro \
                  mame2000 \
                  melonds \
                  meowpc98 \
                  mgba \
                  mrboom \
                  mu \
                  mupen64plus_next \
                  neocd \
                  nestopia \
                  np2kai \
                  nxengine \
                  o2em \
                  openlara \
                  opera \
                  parallel_n64 \
                  pcsx2 \
                  pcsx_rearmed \
                  picodrive \
                  play \
                  pocketcdg \
                  pokemini \
                  potator \
                  ppsspp \
                  prboom \
                  prosystem \
                  puae \
                  puae2021 \
                  px68k \
                  quasi88 \
                  quicknes \
                  race \
                  reminiscence \
                  retro8 \
                  same_cdi \
                  sameboy \
                  sameduck \
                  scummvm \
                  snes9x \
                  snes9x2002 \
                  snes9x2005 \
                  snes9x2005_plus \
                  snes9x2010 \
                  stella \
                  stella2014 \
                  superbroswar \
                  swanstation \
                  tgbdual \
                  theodore \
                  tic80 \
                  tyrquake \
                  uae4arm \
                  uzem \
                  vbam \
                  vecx \
                  vice \
                  virtualjaguar \
                  wasm4 \
                  xmil \
                  xrick \
                  yabause \
                 " BUILDER_NAME=ilmich BUILD_PERIODIC=nightly PROJECT=Rockchip DEVICE=RK322x ARCH=arm UBOOT_SYSTEM=rk322x make image
